### ISSUE TITLE
markdown 如何实现

### ISSUE THREAD

**Issue by iiijarvis** [youknowznm/vue-memo#3]
您好，想请问那个markdown编辑是如何具体实现的？？？
想参考一下

**Comment by youknowznm** [comment]
@lao42981894zh  https://github.com/chjj/marked 提供的 marked() 方法可以接受一个 markdown 字符串，返回渲染出的 HTML

不太确定您是不是想问这个哈

**Comment by youknowznm** [comment]
@lao42981894zh 您可以 fork 过去一下跑一遍，再看下代码就清楚了

**Comment by iiijarvis** [comment]
OK 
谢谢
