### ISSUE TITLE
写得很不错，我有两个问题请教一下

### ISSUE THREAD

**Issue by Guidozijef** [youknowznm/vue-memo#5]
一、如何实现在编辑文本的时候使用MarkDown语法？
二、数据是存储在什么地方的？能不能直接存储在github或者一写云平台上面？

**Comment by youknowznm** [comment]
@Guidozijef 
1. 是使用 `marked.js` 这个库转换字符串为 html 的.
2. 存在浏览器的 localStorage 内, 这个项目是个不实用的玩具, 没有用到数据库.

比较忙 回复简单 请见谅
